### ISSUE TITLE
adding ssh key results in hung terminal.

### ISSUE THREAD

**Issue by encee** [buildkite/elastic-ci-stack-ssm-secrets-hooks#2]
On the current release for the cloudformation stack https://s3.amazonaws.com/buildkite-aws-stack/v3.2.1/aws-stack.json . The ssh-add command in lib/shared.bash results in a hung terminal. Was able to work around the issue by adding DISPLAY=:0 to the variables before the command.

 i.e. ```env DISPLAY=:0 SSH_ASKPASS='/bin/false' ssh-add -```

**Comment by lox** [comment]
I'm perplexed that `DISPLAY=:0` fixes this for you, typically this would be for use in a GUI environment where there are multiple displays in play. How did you arrive at that fix?

I'll try and reproduce on a recent stack!

**Comment by encee** [comment]
I am not entirely sure that DISPLAY=:0 resolved it the more I think on it, I was altering other pieces at the same time. Apologies but this was a bit ago...  If you don't encounter the same issue this might of been resolved with changes to the type of secret it was.
